# Generated by Django 4.2.11 on 2024-11-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_purchase_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='background_images/'),
        ),
    ]
