# Generated by Django 4.2.16 on 2024-11-09 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_favorite_artist_alter_favorite_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='artist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='app.artist'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='app.product'),
        ),
    ]
