# Generated by Django 4.2.16 on 2024-11-09 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_favorite_artist_alter_favorite_product'),
    ]

    operations = [
    ]
