# Generated by Django 4.2.11 on 2024-11-09 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_favoriteartist_artist'),
        ('app', '0032_alter_product_addedproduct'),
    ]

    operations = [
    ]
