# Generated by Django 4.2.11 on 2024-11-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_merge_20241109_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='discount_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
