# Generated by Django 4.2.16 on 2024-11-09 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_merge_20241109_2202'),
        ('app', '0037_merge_20241109_2328'),
    ]

    operations = [
    ]
