# Generated by Django 5.1.2 on 2024-10-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_artist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='app.clothing')),
            ],
        ),
    ]
