# Generated by Django 5.1.2 on 2024-10-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_clothing_size_remove_product_stock_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='stock',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='cd',
            name='stock',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='vinil',
            name='stock',
            field=models.IntegerField(default=30),
        ),
    ]
