# Generated by Django 5.1.2 on 2024-10-28 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_accessory_stock_cd_stock_vinil_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addedProduct',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
