# Generated by Django 5.1.2 on 2024-11-03 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total',
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
