# Generated by Django 4.2.11 on 2024-11-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_cart_products_remove_cart_total_and_more'),
        ('app', '0012_remove_user_profile_picture_user_image_and_more'),
    ]

    operations = [
    ]
