# Generated by Django 4.2.11 on 2024-11-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_user_country_alter_user_email'),
        ('app', '0014_user_company_user_user_type_alter_company_id'),
    ]

    operations = [
    ]
