# Generated by Django 5.1.3 on 2024-11-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20241105_1528'),
        ('app', '0015_merge_20241105_1531'),
        ('app', '0016_alter_user_company'),
    ]

    operations = [
    ]
