# Generated by Django 4.2.11 on 2024-11-09 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_favorite_artist_alter_favorite_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteartist',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoritesArtist', to='app.artist'),
        ),
    ]
