# Generated by Django 4.2.16 on 2024-11-09 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_favoriteartist_artist_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.artist'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=30, null=True),
        ),
    ]
