# Generated by Django 4.2.16 on 2024-11-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_merge_20241109_1515'),
        ('app', '0033_merge_20241109_1847'),
    ]

    operations = [
    ]
