# Generated by Django 4.2.16 on 2024-11-09 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_merge_20241109_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteartist',
            name='artist',
        ),
        migrations.AddField(
            model_name='favoriteartist',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favoriteCompany', to='app.company'),
        ),
        migrations.AlterField(
            model_name='favoriteartist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteCompany', to=settings.AUTH_USER_MODEL),
        ),
    ]
