# Generated by Django 4.2.11 on 2024-11-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_purchase_discount_applied_purchase_discount_value'),
        ('app', '0036_remove_favoriteartist_company_favoriteartist_artist_and_more'),
    ]

    operations = [
    ]
