# Generated by Django 5.1.4 on 2024-12-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_chat_message'),
        ('app', '0043_user_balance'),
    ]

    operations = [
    ]
