# Generated by Django 5.1.4 on 2024-12-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_chat_last_company_timestamp_chat_last_user_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
