# Generated by Django 5.1.4 on 2024-12-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.FloatField(default=0),
        ),
    ]
